name:                crik-cli
version:             0.1.0.0
github:              "githubuser/crik-cli"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/crik-cli#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  crik:
    main: Crik/Main.hs
    other-modules:
    - Crik.Client
    - Crik.CrudCommands
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson >= 1.0 && <= 2.0
    - bytestring >= 0.10 && <= 0.11
    - crik-types
    - http-client >= 0.5
    - optparse-applicative
    - servant
    - servant-client >= 0.13
    - text >= 1.0 && <= 2.0
